Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 591, in snakemake
    workflow.include(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 1173, in include
    exec(compile(code, snakefile, "exec"), self.globals)
  File "/home/jeszyman/repos/cfdna-frag/workflow/int_test.yaml", line 6, in <module>
KeyError: 'frag_dir'

KeyError in line 6 of /home/jeszyman/repos/cfdna-frag/workflow/int_test.yaml:
'frag_dir'
  File "/home/jeszyman/repos/cfdna-frag/workflow/int_test.yaml", line 6, in <module>
